changelog:
  exclude:
    labels:
      - "release:ignore"

  categories:
    - title: Breaking Changes ⚠
      labels:
        - "semver:major"
    - title: Exciting New Features 🎉
      labels:
        - "semver:minor"
    - title: Bug Fixes 🐛
      labels:
        - "semver:patch"
    - title: Other Changes
      labels:
        - "*"