changelog:
  exclude:
    labels:
      - "release:ignore"

  categories:
    - title: Major Updates (Breaking Changes ⚠)
      labels:
        - "semver:major"

    - title: Minor Updates (New Features 🎉 and other non-breaking API changes)
      labels:
        - "semver:minor"

    - title: Patches (Bug Fixes 🐛, refactoring, and other changes that don't affect the existing API)
      labels:
        - "semver:patch"